// eslint-disable-next-line import/no-anonymous-default-export
export default [
  {
    id: 1,
    img: "",
    name: "Emille",
    message: "Hello, How are you?",
    count: 2,
    time: "03:04",
    zone: "PM",
  },
  {
    id: 2,
    img: "",
    name: "Kwizera John",
    message: "I think we should do this in a group",
    count: 1,
    time: "09:030",
    zone: "AM",
  },
  {
    id: 3,
    img: "https://media.licdn.com/dms/image/D4E03AQHr2n5ivKrvaw/profile-displayphoto-shrink_200_200/0/1690097978013?e=2147483647&v=beta&t=N5mqcDi5fGLt90Lanor0LeU8-SxK0ri4MchYZAP2aJE",
    name: "Habumugisha",
    message: "What are your thoughts on this?",
    count: 4,
    time: "11:030",
    zone: "AM",
  },
  {
    id: 4,
    img: "",
    name: "Rukundo",
    message: "Have you checked your mail box",
    count: 1,
    time: "08:12",
    zone: "PM",
  },

  {
    id: 5,
    img: "",
    name: "Mutesi Annet",
    message: "Done",
    count: 1,
    time: "08:24",
    zone: "AM",
  },
  {
    id: 6,
    img: "",
    name: "Siribobo",
    message: "Idk if you're right!",
    count: 11,
    time: "08:12",
    zone: "PM",
  },
  {
    id: 7,
    img: "",
    name: "Mutoni",
    message: "I see myself using this method",
    count: 6,
    time: "05:42",
    zone: "PM",
  },
  {
    id: 8,
    img: "",
    name: "Tracy",
    message: "Combine them together",
    count: 1,
    time: "00:02",
    zone: "AM",
  },
];
